// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: company.proto

package qgenda

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
	sql "sql"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Company struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//(gogoproto.customtype) = "github.com/gogo/protobuf/test/custom.Uint128"
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Abbreviation         string                 `protobuf:"bytes,3,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	Createdtime          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdtime,proto3" json:"createdtime,omitempty"`
	SillyBillyGoat       string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Phonenumber          string                 `protobuf:"bytes,6,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Profile              []*Profile             `protobuf:"bytes,7,rep,name=profile,proto3" json:"profile,omitempty"`
	Organization         []*Organization        `protobuf:"bytes,8,rep,name=organization,proto3" json:"organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}
func (*Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_ade57ca5b8f3903f, []int{0}
}
func (m *Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Company.Unmarshal(m, b)
}
func (m *Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Company.Marshal(b, m, deterministic)
}
func (m *Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Company.Merge(m, src)
}
func (m *Company) XXX_Size() int {
	return xxx_messageInfo_Company.Size(m)
}
func (m *Company) XXX_DiscardUnknown() {
	xxx_messageInfo_Company.DiscardUnknown(m)
}

var xxx_messageInfo_Company proto.InternalMessageInfo

func (m *Company) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Company) GetAbbreviation() string {
	if m != nil {
		return m.Abbreviation
	}
	return ""
}

func (m *Company) GetCreatedtime() *timestamppb.Timestamp {
	if m != nil {
		return m.Createdtime
	}
	return nil
}

func (m *Company) GetSillyBillyGoat() string {
	if m != nil {
		return m.SillyBillyGoat
	}
	return ""
}

func (m *Company) GetPhonenumber() string {
	if m != nil {
		return m.Phonenumber
	}
	return ""
}

func (m *Company) GetProfile() []*Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Company) GetOrganization() []*Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

// Profile appears to link a user role to a company...
type Profile struct {
	Name                 *sql.NullString `protobuf:"bytes,1,opt,name=name,proto3,customtype=sql.NullString" json:"name,omitempty"`
	Key                  string          `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Admin                bool            `protobuf:"varint,3,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_ade57ca5b8f3903f, []int{1}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Profile) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

// Organization appears to linke multiple companies and users
type Organization struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_ade57ca5b8f3903f, []int{2}
}
func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*Company)(nil), "qgenda.Company")
	proto.RegisterType((*Profile)(nil), "qgenda.Profile")
	proto.RegisterType((*Organization)(nil), "qgenda.Organization")
}

func init() { proto.RegisterFile("company.proto", fileDescriptor_ade57ca5b8f3903f) }

var fileDescriptor_ade57ca5b8f3903f = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x3d, 0x4f, 0xeb, 0x30,
	0x14, 0x55, 0xd2, 0x8f, 0xf4, 0xdd, 0xf4, 0xf5, 0x3d, 0x59, 0x1d, 0xa2, 0x2e, 0x8d, 0x32, 0x3c,
	0xf5, 0x2d, 0xae, 0x54, 0x18, 0x18, 0x98, 0xca, 0xc0, 0x06, 0x28, 0x65, 0x61, 0x74, 0x1a, 0xd7,
	0x58, 0x38, 0x76, 0xea, 0xba, 0x48, 0xe5, 0x07, 0xf2, 0x23, 0x18, 0x3a, 0xf0, 0x4b, 0x50, 0xec,
	0xa4, 0xa4, 0x62, 0xb1, 0xee, 0x3d, 0xe7, 0xe8, 0xf8, 0xe8, 0x5c, 0xf8, 0xbd, 0x56, 0x45, 0x49,
	0xe4, 0x01, 0x97, 0x5a, 0x19, 0x85, 0xfa, 0x5b, 0x46, 0x65, 0x4e, 0x26, 0x53, 0xa6, 0x14, 0x13,
	0x74, 0x6e, 0xd1, 0x6c, 0xbf, 0x99, 0x1b, 0x5e, 0xd0, 0x9d, 0x21, 0x45, 0xe9, 0x84, 0x93, 0x84,
	0x29, 0xa6, 0xbe, 0xe9, 0x6a, 0xb3, 0x8b, 0x9d, 0x9c, 0x26, 0x79, 0xf7, 0x21, 0xb8, 0x71, 0xf6,
	0x68, 0x04, 0x3e, 0xcf, 0x23, 0x2f, 0xf6, 0x66, 0xbf, 0x52, 0x9f, 0xe7, 0x08, 0x41, 0x57, 0x92,
	0x82, 0x46, 0xbe, 0x45, 0xec, 0x8c, 0x12, 0x18, 0x92, 0x2c, 0xd3, 0xf4, 0x95, 0x13, 0xc3, 0x95,
	0x8c, 0x3a, 0x96, 0x3b, 0xc3, 0xd0, 0x35, 0x84, 0x6b, 0x4d, 0x89, 0xa1, 0x79, 0x95, 0x28, 0xea,
	0xc6, 0xde, 0x2c, 0x5c, 0x4c, 0xb0, 0x8b, 0x8b, 0x9b, 0x3c, 0xf8, 0xb1, 0x89, 0x9b, 0xb6, 0xe5,
	0x08, 0xc3, 0x40, 0xa8, 0xb5, 0x73, 0xef, 0x55, 0xee, 0x4b, 0xf4, 0x79, 0x9c, 0x8e, 0x56, 0x5c,
	0x88, 0xc3, 0xb2, 0x7a, 0x6e, 0x15, 0x31, 0xe9, 0x49, 0x83, 0x62, 0x08, 0xcb, 0x67, 0x25, 0xa9,
	0xdc, 0x17, 0x19, 0xd5, 0x51, 0xdf, 0x06, 0x6a, 0x43, 0xe8, 0x3f, 0x04, 0xa5, 0x56, 0x1b, 0x2e,
	0x68, 0x14, 0xc4, 0x9d, 0x59, 0xb8, 0xf8, 0x83, 0x5d, 0x85, 0xf8, 0xc1, 0xc1, 0x69, 0xc3, 0xa3,
	0x2b, 0x18, 0x2a, 0xcd, 0x88, 0xe4, 0x6f, 0x2e, 0xc0, 0xc0, 0xea, 0xc7, 0x8d, 0xfe, 0xbe, 0xc5,
	0xa5, 0x67, 0xca, 0xe4, 0x09, 0x82, 0xda, 0x0d, 0xfd, 0xab, 0x7b, 0xf3, 0x5c, 0xfa, 0x8f, 0xe3,
	0x74, 0xb4, 0xdb, 0x0a, 0x7c, 0xb7, 0x17, 0x62, 0x65, 0x34, 0x97, 0xac, 0xee, 0xf2, 0x2f, 0x74,
	0x5e, 0xe8, 0xa1, 0xae, 0xb7, 0x1a, 0xd1, 0x18, 0x7a, 0x24, 0x2f, 0xb8, 0xab, 0x75, 0x90, 0xba,
	0x25, 0xb9, 0x84, 0x61, 0xfb, 0xe3, 0xd3, 0x5d, 0xbc, 0xd6, 0x5d, 0x7e, 0x78, 0x65, 0x7d, 0x5b,
	0xf4, 0xc5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x98, 0xc3, 0x22, 0x3e, 0x02, 0x00, 0x00,
}
